think_phrases = [
    "alternatively",
    "as a result",
    "assume",
    "because",
    "calculate",
    "check",
    "compute",
    "confirm",
    "consequently",
    "consider",
    "define",
    "determine",
    "does not work",
    "doesn't work",
    "error",
    "evaluate",
    "finally",
    "find",
    "first",
    "firstly",
    "for example",
    "for instance",
    "get",
    "given there",
    "hence",
    "however",
    "if",
    "makes sence",
    "next",
    "not correct",
    "not working",
    "now",
    "re-calculate",
    "re-evaluate",
    "recalculate",
    "reevaluate",
    "since",
    "so",
    "solved",
    "step",
    "still not",
    "summarize",
    "then",
    "thereby",
    "therefore",
    "thus",
    "to",
    "try",
    "verify",
    "wait"
]
